name: CI Workflow

on:
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [20.17.0]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Uninstall old Expo CLI
      run: npm uninstall -g expo-cli

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Remove node_modules
      run: rm -rf node_modules

    - name: Install dependencies
      run: npm install

    - name: Install latest Expo CLI
      run: npm install -g expo-cli

    - name: Start Expo project in background
      run: npx expo start --no-dev --minify & echo $! > expo.pid

    # Add a delay or timeout here
    - name: Wait for 30 seconds
      run: sleep 30

    # Kill the Expo process so it doesn't timeout
    - name: End Expo project
      run: kill -9 $(cat expo.pid) || true

    # Clean up
    - name: Remove PID file
      run: rm expo.pid || true

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install Python dependencies from requirements.txt
    - name: Install Python dependencies
      run: pip install -r requirements.txt
     
    # Install flake8 
    - name: Install flake8
      run: pip install flake8
  
    # Run Flake8 Linter
    - name: Run Flake8 Linter
      run: flake8 back-end/app.py

      # Run npm linter
    - name: Run npm Linter
      run: 
        npm run lint