name: CI Workflow

on:
  push: 
    branches: 
      - main
      - ms-testing-build
  pull_request: 
    branches: 
      - main
      - ms-testing-build

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x] # Trying different Node.js versions

    steps:
    # Checkout code
    - uses: actions/checkout@v4

    # Setup Node.js version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Clean npm cache and remove node_modules for recent issue
    - name: Clean npm cache
      run: npm cache clean --force

    - name: Remove node_modules
      run: rm -rf node_modules

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Install latest Expo CLI
    - name: Install latest Expo CLI
      run: npm install -g expo-cli

    # Install TypeScript types if using TypeScript
    - name: Install TypeScript types
      run: npm install --save-dev @types/react-native

    # Start Expo project
    - name: Start Expo project
      run: npm run ios
