name: CI Workflow

on:
  push: 
    branches: 
      - main
      - ms-testing-build
  pull_request: 
    branches: 
      - main
      - ms-testing-build
  
jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [20.17.0]

    steps:
    # checkout code
    - uses: actions/checkout@v4

    # Setup Node.js version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Install Expo CLI
    - name: Install Expo CLI
      run: npm install -g expo-cli

    # build project
    - name: Build project
      run: expo start --no-dev --minify