name: Tune Timer CI

on:
  push: 
    branches: [ $default-branch ]
  pull_request: 
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    # Testing and setup of the work environment
    - name: Run a one-line script as a test
      run: echo Hi! from Tune Timer
   
    # Build the project
    - name: Build
      run: swift build -v

    # Run tests
    - name: Run tests
      run: swift test -v

    # Upload test results (optional)
    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: .build/debug/test-results
